[package]
name = "calabaza-factions"
version = "0.4.3"
edition = "2024"
license = "MIT"
description = "Hardcore faction and guild system for PumpkinMC"
repository = "https://github.com/MaharlikaPMDev/CalabazaFactions"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pumpkin-plugin-api = { git = "https://github.com/Pumpkin-MC/Pumpkin", rev = "c01ddb7b65b0be9641eb2273740ce8e1a04b7807", package = "pumpkin-plugin-api" }
tracing = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.9"

[profile.release]
lto = true
codegen-units = 1
opt-level = "s"
strip = true
