[package]
name = "calabaza-factions"
version = "0.4.0"
edition = "2024"
license = "MIT"
description = "Hardcore faction and guild system for PumpkinMC"
repository = "https://github.com/MaharlikaPMDev/CalabazaFactions"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
pumpkin-plugin-api = { git = "https://github.com/Pumpkin-MC/Pumpkin", rev = "20c51d346e33f1f485f401b6d159a9f0881ec1af", package = "pumpkin-plugin-api" }
tracing = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.9"

[profile.release]
lto = true
codegen-units = 1
opt-level = "s"
strip = true
